# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: jailsonzarur
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: desafiobgcbrasil
# "service" is the name of this project. This will also be added to your AWS resource names.
service: api-bestsellers

stages:
  default:
    params:
      tableName: "bestsellers-table-${sls:stage}"

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [BestSellersTable, Arn]
  environment:
    BEST_SELLERS_TABLE: ${param:tableName}

functions:      
  api:
    handler: app/handlers/handler.handler
    description: Health Check
    events:
      - http:
          path: /
          method: get
  getLastBestSellers:
    handler: app/handlers/getLastBestSellers.handler
    description: Get Last Scraping of Best Seller from Amazon
    environment:
      BEST_SELLERS_TABLE: ${param:tableName}
    events:
      - http:
          path: /last-best-sellers-scraping
          method: get
  getAllBestSellers:
    handler: app/handlers/getAllBestSellers.handler
    description: Get All Best Seller Scrapings from Amazon
    environment:
      BEST_SELLERS_TABLE: ${param:tableName}
    events:
      - http:
          path: /all-best-sellers-scraping
          method: get

resources:
  Resources:
    BestSellersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: bestSellerId
            AttributeType: S
        KeySchema:
          - AttributeName: bestSellerId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:tableName}
